### ISSUE TITLE
Doesn't really look linear to me

### ISSUE THREAD

**Issue by sctcooper** [kiosklabs/kaggle-titanic-competition#1]
Hey, the tutorial in the branch seems to have an issue. it seems to require a few non standard libraries. Can you double check the code?

**Comment by kiosklabs** [comment]
hey scott, what's not linear? can you post the issue here?

**Comment by sctcooper** [comment]
I mean, the relationship of some of the predictors you suggested. I think I'm having problems with my old installation of scikit. It looks similar to this: http://stackoverflow.com/questions/36840496/conda-update-scikit-learn-also-scipy-and-numpy

**Comment by kiosklabs** [comment]
oh, you mean in the notebook kernel itself? let's transfer over to chat, so we could screen cap.

**Comment by sctcooper** [comment]
sure. I'll update the readme later, if that's okay.
